CREATE DATABASE escola;
USE escola;

CREATE TABLE tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    problema TEXT NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);